apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: to-do-ingress
  namespace: to-do-ns
spec:
  rules:
  - host: todo.my.com
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: to-do-api-service
            port:
              number: 4000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: to-do-app-service
            port:
              number: 3000